version: '3.9'
services:
  frontend:
    image: k444mczi/rsww_180066_frontend:2.0
    ports:
      - "18006:80"
    environment:
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:9092
    networks:
      - travel-net
  notification:
    image: k444mczi/rsww_180066_notification:2.0
    deploy:
      replicas: 3
    environment:
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:9092
      - BROKER_RELAY_HOST=activemq
    networks:
      - travel-net
  gateway:
    image: k444mczi/rsww_180066_gateway:2.0
    depends_on:
      - eureka
    networks:
      - travel-net
  eureka:
    image: k444mczi/rsww_180066_eurekaserver:latest
    networks:
      - travel-net
  activemq:
    image: k444mczi/rsww_180066_activemq:latest
    environment:
      - EUREKA_URI=http://eureka:8761/eureka
      - BROKER_HOST=0.0.0.0
    networks:
      - travel-net
  offer_write:
    image: k444mczi/rsww_180066_offerwrite:2.0
    deploy:
      replicas: 2
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/rsww_180066_offer
      - SPRING_DATASOURCE_USERNAME=student
      - SPRING_DATASOURCE_PASSWORD=student
      - ESDB_CONNECTIONSTRING=esdb://eventstore:2113?tls=false
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:9092
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    depends_on:
      - event_store
    networks:
      - travel-net
  order:
    image: k444mczi/rsww_180066_order:2.0
    networks:
      - travel-net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/rsww_180066_order
      - SPRING_DATASOURCE_USERNAME=student
      - SPRING_DATASOURCE_PASSWORD=student
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:9092
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
  payment:
    image: k444mczi/rsww_180066_payment:2.0
    networks:
      - travel-net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/rsww_180066_payment
      - SPRING_DATASOURCE_USERNAME=student
      - SPRING_DATASOURCE_PASSWORD=student
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:9092
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
  offer_read:
    image: k444mczi/rsww_180066_offerread:2.0
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo_read_model
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=rsww_180066_offer_read
    depends_on:
      - kafka
    networks:
      - travel-net
  tour_operator:
    image: k444mczi/rsww_180066_touroperator:2.0
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/rsww_180066_tour_operator
      - SPRING_DATASOURCE_USERNAME=student
      - SPRING_DATASOURCE_PASSWORD=student
      - BOOTSTRAP_SERVER=kafka:9092
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:9092
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    depends_on:
      - kafka
    networks:
      - travel-net
  eventstore:
    image: eventstore/eventstore
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    networks:
      - travel-net
    volumes:
      - ./volumes/eventstore-volume-data:/var/lib/eventstore
      - ./volumes/eventstore-volume-logs:/var/log/eventstore
  zookeeper:
    hostname: zookeeper
    image: 'zookeeper:3.8.2'
    volumes:
      - ./volumes/zoo-stack-data:/tmp/zookeeper
    deploy:
      replicas: 3
      placement:
        constraints: [ node.role == manager ]
    networks:
      - travel-net
  kafka:
    image: 'bitnami/kafka:3.5.1'
    hostname: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MAX_REQUEST_SIZE: 20971520
      KAFKA_CFG_MAX_REQUEST_SIZE: 20971520
      KAFKA_CFG_PRODUCER_MAX_REQUEST_SIZE: 20971520
    networks:
      - travel-net
  postgres:
    image: postgres:15.4
    deploy:
      placement:
        constraints: [ node.role == manager ]
    environment:
      POSTGRES_PASSWORD: student
      POSTGRES_USER: student
      POSTGRES_DB: offer
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data
    ports:
      - "18007:5432"
    networks:
      - travel-net
  mongo_read_model:
    image: mongo:4.4.9
    deploy:
      placement:
        constraints: [ node.role == manager ]
    environment:
      MONGO_INITDB_DATABASE: rsww_180066_offer_read
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - travel-net
networks:
  travel-net:
    driver: overlay
    name: RSWW-180066-NETWORK
  mongo-net:
    external: true
    name: admin-mongodb_default
  postgres-net:
    external: true
    name: admin-postgres_default