version: '3'
services:
  frontend:
    container_name: frontend
    image: k444mczi/rsww_180066_frontend:latest
    environment:
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:9092
    networks: 
      - rsww-180066-network
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "18006:80"
    depends_on:
      - frontend
      - gateway
    networks:
      - rsww-180066-network
  notification:
    container_name: notification
    image: k444mczi/rsww_180066_notification:latest
    environment:
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:9092
    networks:
      - rsww-180066-network
  gateway:
    image: k444mczi/rsww_180066_gateway:latest
    depends_on:
      - eureka
    networks:
      - rsww-180066-network
  eureka:
    image: k444mczi/rsww_180066_eureka:latest
    networks:
      - rsww-180066-network
  offer_write:
    image: k444mczi/rsww_180066_offer_write:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/offer
      - SPRING_DATASOURCE_USERNAME=student
      - SPRING_DATASOURCE_PASSWORD=student
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - ESDB_CONNECTIONSTRING=esdb://eventstore:2113?tls=false
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:9092
    depends_on:
      - event_store
      - postgres
    networks:
      - rsww-180066-network
  order:
    container_name: order
    image: k444mczi/rsww_180066_order:latest
    networks:
      - rsww-180066-network
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/order
      - SPRING_DATASOURCE_USERNAME=student
      - SPRING_DATASOURCE_PASSWORD=student
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:9092
  payment:
    container_name: payment
    image: k444mczi/rsww_180066_payment:latest
    networks:
      - rsww-180066-network
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/payment
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=student
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:9092
  offer_read:
    container_name: offer_read
    image: k444mczi/rsww_180066_offer_read:latest
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo_read_model
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=offer_read_model
    depends_on:
      - mongo_read_model
      - kafka
    networks:
      - rsww-180066-network
  tour_operator:
    container_name: tour_operator
    image: k444mczi/rsww_180066_tour_operator:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/tour_operator
      - SPRING_DATASOURCE_USERNAME=student
      - SPRING_DATASOURCE_PASSWORD=student
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - BOOTSTRAP_SERVER=kafka:9092
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:9092
    depends_on:
      kafka:
        condition: service_started
      postgres:
        condition: service_started
    networks:
      - rsww-180066-network
  event_store:
    container_name: eventstore
    image: eventstore/eventstore
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    networks:
      - rsww-180066-network
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore
  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: 'zookeeper:3.8.2'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - rsww-180066-network
  kafka:
    image: 'bitnami/kafka:3.5.1'
    container_name: kafka
    hostname: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MAX_REQUEST_SIZE: 20971520
      KAFKA_CFG_MAX_REQUEST_SIZE: 20971520
      KAFKA_CFG_PRODUCER_MAX_REQUEST_SIZE: 20971520
    networks:
      - rsww-180066-network
volumes:
  mongo_read_db:
  eventstore-volume-data:
  eventstore-volume-logs:
  postgres_data:
networks:
  rsww-180066-network:
    driver: overlay