spring:
  application:
    name: Gateway
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
      default-filters: DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Headers
      globalcors:
        corsConfigurations:
          '[/**]':
            allowed-origin-patterns:
              - '*'
            allowedMethods:
              - '*'
            allowed-headers:
              - '*'
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: Payment
          uri: lb://Payment
          predicates:
            - Path=/payment/accept,
              /payment/cancel
        - id: OfferRead
          uri: lb://OfferRead
          predicates:
            - Path=/offers/**,/locations
        - id: OfferWrite
          uri: lb://OfferWrite
          predicates:
            - Path=/test/flights, /test/hotels, /test/offers
        - id: Notification
          uri: lb://notification
          predicates:
            - Path=/initial/**
        - id: NotificationSockJS
          uri: lb://notification
          predicates:
            - Path=/ws/info/**
        - id: NotificationWS
          uri: lb:ws://notification
          predicates:
            - Path=/ws/**
        - id: Order
          uri: lb://Order
          predicates:
            - Path=/order/create
        - id: TourOperator
          uri: lb://TourOperator
          predicates:
            - Path=/init, /flights/send, /hotels/send, /busses/send, /to-update/start, /to-update/stop
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
  instance:
    preferIpAddress: true