spring:
  application:
    name: Gateway
  cloud:
    gateway:
      default-filters: DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Headers
      globalcors:
        corsConfigurations:
          '[/**]':
            allowed-origin-patterns:
              - '*'
            allowedMethods:
              - '*'
            allowed-headers:
              - '*'
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: OfferRead
          uri: lb://OfferRead
          predicates:
            - Path=/offers/**,/locations
        - id: OfferWrite
          uri: lb://OfferWrite
          predicates:
            - Path=/test/flights, /test/hotels, /test/offers
        - id: Notification
          uri: lb://notification
          predicates:
            - Path=/initial/**
        - id: NotificationSockJS
          uri: lb://notification
          predicates:
            - Path=/ws/info/**
        - id: NotificationWS
          uri: lb:ws://notification
          predicates:
            - Path=/ws/**
        - id: Order
          uri: lb://order
          predicates:
            - Path=/order/**
        - id: TourOperator
          uri: lb://TourOperator
          predicates:
            - Path=/init, /flights/send, /hotels/send, /busses/send
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
  instance:
    preferIpAddress: true