spring:
  application:
    name: Gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: '*'
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: OFFERS_READ
          uri: lb://offer_read
          predicates:
            - Path=/offers/**
          filters:
          #            - TokenRelay=
        - id: NOTIFICATIONS
          uri: lb://notifications
          predicates:
            - Path=/ws/**, /notifications/**, /initial/**
          filters:
          #            - TokenRelay=
#        - id: ORDERS
#          uri: lb://order
#          predicates:
#            - Path=/orders/**
#          filters:
##            - TokenRelay=
#        - id: PAYMENTS
#          uri: lb://payments
#          predicates:
#            - Path=/payments/**
#          filters:
#      #            - TokenRelay=
eureka:
    client:
      serviceUrl:
        defaultZone: http://eureka:8761/eureka/  # Zaktualizuj tę wartość do odpowiedniej nazwy hosta serwera Eureka
