spring:
  application:
    name: Gateway
  cloud:
    gateway:
      default-filters: DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Headers
      globalcors:
        corsConfigurations:
          '[/**]':
            allowed-origin-patterns:
              - '*'
            allowedMethods:
              - '*'
            allowed-headers:
              - '*'
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: OFFERS_READ
          uri: lb://offer_read
          predicates:
            - Path=/offers/**
          filters:
          #            - TokenRelay=
        - id: NOTIFICATIONS
          uri: lb://notification
          predicates:
            - Path=/initial/**
        - id: websocket-sockjs-route
          uri: lb://notification
          predicates:
            - Path=/ws/info/**
        - id: websocket_route
          uri: lb:ws://notification
          predicates:
            - Path=/ws/**
          #            - TokenRelay=
#        - id: ORDERS
#          uri: lb://order
#          predicates:
#            - Path=/orders/**
#          filters:
##            - TokenRelay=
#        - id: PAYMENTS
#          uri: lb://payments
#          predicates:
#            - Path=/payments/**
#          filters:
#      #            - TokenRelay=
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true